#Playbook to set up EC2 instance 
# 1st Task - Creates a custom security group
# 2nd Task - Spins up new EC2 instances
# 3nd Task - Waits for ssh to become active on instance

#########################################################

- hosts: localhost
  
  tasks: 

    - name: Setting up Security/Firewall group
      ec2_group:
        name: My_AWS_Sec_Grp
        description: Rules allowing traffic on port 22 and 80
        region: us-west-2
        rules: 
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0

    - name: Provisioning a EC2 instance
       ec2:
          key_name: RajAWSkey
          region: us-west-2
          instace_type: t2.micro
          image: ami-775e4f16
          wait: yes
          wait_timeout: 500
          count: 1
          instance_tags:
            Name: awslabserver
            Owner: Rajesh
          monitoring: no
          vpc_subnet_id: subnet-920b30f6
          assign_public_ip: yes
          group: My_AWS_Sec_Grp
        register: ec2_out

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      wait_items: '{{ec2_out.instances}}'





